// AUTO-GENERATED by scripts/upload-public-assets.mjs
// DO NOT EDIT MANUALLY. Re-run the script to regenerate.
// Generated: 2026-04-20T00:07:00.966Z

export const STATIC_AVATARS = {
    kids: [
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_1.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_2.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_3.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_4.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_5.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_6.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_7.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/kids/kid_8.png"
    ],
    female: [
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_1.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_2.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_3.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_4.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_5.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_6.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_7.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/female/girl_8.png"
    ],
    male: [
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_1.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_2.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_3.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_4.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_5.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_6.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_7.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/male/boy_8.png"
    ],
    animals: [
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_1.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_2.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_3.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_4.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_5.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_6.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_7.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_8.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_9.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_10.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_11.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_12.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_13.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_14.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_15.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/animals/animal_16.png"
    ],
    monsters: [
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_1.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_2.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_3.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_4.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_5.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_6.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_7.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_8.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_9.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_10.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_11.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_12.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_13.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_14.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_15.png",
            "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/avatars/monsters/monster_16.png"
    ],
} as const;

export const STATIC_REVIEWS: readonly string[] = [
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review1.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review2.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review3.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review4.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review5.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review6.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review7.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review8.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review9.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review10.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review11.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review12.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review13.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review14.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review15.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review16.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review17.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review18.jpg",
    "https://storage.googleapis.com/kruheem-course-45088.firebasestorage.app/static/reviews/review19.jpg"
];
